Default Parameter Value blog post
PowerShell/Community-Blog pull request #80
Opened 2021-11-24 15:30 UTC by doctordns

# PR Summary
A new post on $PSDefaultParameterValues variable. 

## PR Checklist

- Do you want this post to be published on a specific date?: Y/N [Specify date]:
- [ ] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [ ] PR has a meaningful title
- [ ] Includes content related an open issue
  - see [Closing issues using keywords][key].
- [ ] This PR is ready to merge and is not **Work in Progress**

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

2021-12-03 22:19 UTC, sdwheeler requested changes
See my suggestions inline.

I noticed a lot of inconsistent formatting. Please review the style guide again.

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +**Q:** When I use cmdlets like `Receive-Job` and `Format-Table`, how do I change default values of **-Keep** and **-Wrap**?
```suggestion
**Q:** When I use cmdlets like `Receive-Job` and `Format-Table`, how do I change default values of the **Keep** and **Wrap** parameters?
```

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +I'm sure you have seen this (and know how to use -Wrap), like this:
```suggestion
I'm sure you have seen this (and know how to use **Wrap**), like this:
```

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +So, the question is: how to tell PowerShell to always use -Wrap when using `Format-Table` or `Format-List`.
```suggestion
So, the question is: how to tell PowerShell to always use `-Wrap` when using `Format-Table` or `Format-List`?
```

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +## The **$PSDefaultParameters** automatic variable
```suggestion
## The `$PSDefaultParameters` automatic variable
```

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +When Powershell (and Windows PowerShell ) starts, it creates the `$PSDefaultParameters' automatic variable.
```suggestion
When PowerShell (and Windows PowerShell) starts, it creates the `$PSDefaultParameters` automatic variable.
```

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +By default the variable is empty when you start PowerShell.
```suggestion
By default, the variable is empty when you start PowerShell.
```

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +The hash table key is the name of the hash table, followed by a ":", and then the name of the parameter.
```suggestion
The hash table key is the name of the cmdlet, followed by a colon (`:`), and then the name of the parameter.
```

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +If you wanted, for example, to always use **-Wrap** for the `Format-*` cmdlets, you could do this:
```suggestion
If you wanted, for example, to always use the **Wrap** parameter for the `Format-*` cmdlets, you could do this:
```

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +Any change you make to the **$PSDefaultParameterValues** variable is only applicable for the current session.
```suggestion
Any change you make to the `$PSDefaultParameterValues` variable is only applicable for the current session.
```

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +On my development box, I use the following snippet in side my **$Profile** file:
```suggestion
On my development box, I use the following snippet inside my `$PROFILE` script:
```

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +$PSDefaultParameterValues.Add('*:Wrap', $true
I think you meant for those parameters to apply to the `Format-*` cmdlets.

```suggestion
$PSDefaultParameterValues.Add('Format-*:AutoSize', $true)
$PSDefaultParameterValues.Add('Format-*:Wrap', $true)
$PSDefaultParameterValues.Add('Receive-Job:Keep', $true)
```

2021-12-03 22:19 UTC, sdwheeler commented on Posts/2021/12/tfl-params.md
> +You can read more about `$PSDefaultParameterValues`, and other preference variables in [about_Preference_Variables](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_
```suggestion
You can read more about `$PSDefaultParameterValues`, and other preference variables in [about_Preference_Variables](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_preference_variables#psdefaultparametervalues). 
And for more details of parameter default values, see the [about_Parameters_Default_Values help file](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_parameters_default_values).

```

2021-12-07 10:27 UTC, doctordns commented
It has been a very bad few weeks here - apologies for it taking so long to resolve these.

I think I have fixed these and this is therefore ready to go.

2021-12-07 14:29 UTC, sdwheeler approved these changes

2021-12-07 14:29 UTC, merged