New post on preference behaviour and the role of modules on inheritance.
PowerShell/Community-Blog pull request #81
Opened 2021-11-28 20:38 UTC by jhoneill

# PR Summary

## PR Checklist

- Do you want this post to be published on a specific date?: N (I have put it a folder for December 2021):
- [X] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [X] PR has a meaningful title
- [ ] Includes content related an open issue
  - see [Closing issues using keywords][key].
- [X] This PR is ready to merge and is not **Work in Progress**

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

2021-11-28 20:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PowerShell/Community-Blog?pullRequest=81) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PowerShell/Community-Blog?pullRequest=81) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PowerShell/Community-Blog?pullRequest=81) it.</sub>

2021-11-29 15:51 UTC, doctordns commented on Posts/2021/12/jon-preferences.md
> +A *proxy function* will fix that. If two commands have the same name an alias beats a function,
A *proxy function* can fix that. If two commands have the same name an alias beats a function,

2021-11-29 15:55 UTC, doctordns requested changes
Some minor changes but looks good to me.

Have added Sean as another reviewer.

2021-11-29 15:55 UTC, doctordns commented on Posts/2021/12/jon-preferences.md
> +(I don't carry those 3 lines in my head, when I need them I refer to a script Jeffrey Snover wrote long ago.)
Got a gist for that?

2021-11-29 15:55 UTC, doctordns commented on Posts/2021/12/jon-preferences.md
> +prompt and which isn't there *reliably*, will lead to trouble.
prompt and which isn't there *reliably* can lead to trouble.

2021-11-29 15:55 UTC, doctordns commented on Posts/2021/12/jon-preferences.md
> +And I will also want *that* to inherit into my proxy function.
And I also want *that* to inherit into my proxy function.

2021-11-29 20:05 UTC, doctordns commented on Posts/2021/12/jon-preferences.md
> +(I don't carry those 3 lines in my head, when I need them I refer to a script Jeffrey Snover wrote long ago.)
add a link in the blog post?

2021-12-01 19:52 UTC, jhoneill commented on Posts/2021/12/jon-preferences.md
> +(I don't carry those 3 lines in my head, when I need them I refer to a script Jeffrey Snover wrote long ago.)
Link Added

2022-03-31 21:41 UTC, sdwheeler commented
@jhoneill Can you please sign the CLA?

> [![CLA assistant check](https://camo.githubusercontent.com/4c970efeed75dd01f6778bf7e33dec85e4171375cb69acb0927bfc9d437d78d9/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/PowerShell/Community-Blog?pullRequest=81) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PowerShell/Community-Blog?pullRequest=81) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PowerShell/Community-Blog?pullRequest=81) it.

2022-03-31 22:38 UTC, jhoneill commented
> @jhoneill Can you please sign the CLA?
> 
I **thought** I had, but it was telling me I had not, so I have just signed [again], if you want to take another look.

2022-04-01 13:34 UTC, sdwheeler commented
@jhoneill Thanks for signing the CLA. You should only have to do this once per repository. Maybe you signed it for another? Either way, it is signed now. Thanks.

2022-04-01 13:44 UTC, sdwheeler approved these changes

2022-04-01 13:45 UTC, merged